<?xml version='1.0' encoding='UTF-8'?>
<testsuite hostname="C02SP6MPG8WN" name="historical.HistoricalRecorderTest" tests="15" errors="0" failures="15" time="369.662">
                     <properties>
      <property name="jline.esc.timeout" value="0"/><property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/><property name="sun.boot.library.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib"/><property name="java.vm.version" value="25.112-b16"/><property name="user.country.format" value="GB"/><property name="gopherProxySet" value="false"/><property name="java.vm.vendor" value="Oracle Corporation"/><property name="java.vendor.url" value="http://java.oracle.com/"/><property name="path.separator" value=":"/><property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/><property name="file.encoding.pkg" value="sun.io"/><property name="user.country" value="US"/><property name="sun.java.launcher" value="SUN_STANDARD"/><property name="sun.os.patch.level" value="unknown"/><property name="java.vm.specification.name" value="Java Virtual Machine Specification"/><property name="user.dir" value="/Users/chrichiv/nonwork-dev/london-bus-tracker-v3"/><property name="java.runtime.version" value="1.8.0_112-b16"/><property name="java.awt.graphicsenv" value="sun.awt.CGraphicsEnvironment"/><property name="java.endorsed.dirs" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/endorsed"/><property name="os.arch" value="x86_64"/><property name="java.io.tmpdir" value="/var/folders/08/mfn9j_bx1fv3kt1mcgfzp_w40000gn/T/"/><property name="line.separator" value="
"/><property name="java.vm.specification.vendor" value="Oracle Corporation"/><property name="os.name" value="Mac OS X"/><property name="sun.jnu.encoding" value="UTF-8"/><property name="java.library.path" value="/Users/chrichiv/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/><property name="java.specification.name" value="Java Platform API Specification"/><property name="java.class.version" value="52.0"/><property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/><property name="os.version" value="10.11.6"/><property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/><property name="user.home" value="/Users/chrichiv"/><property name="user.timezone" value="Europe/London"/><property name="java.awt.printerjob" value="sun.lwawt.macosx.CPrinterJob"/><property name="file.encoding" value="UTF-8"/><property name="java.specification.version" value="1.8"/><property name="java.class.path" value="/usr/local/Cellar/sbt/0.13.13/libexec/sbt-launch.jar"/><property name="user.name" value="chrichiv"/><property name="jline.shutdownhook" value="false"/><property name="java.vm.specification.version" value="1.8"/><property name="sun.java.command" value="/usr/local/Cellar/sbt/0.13.13/libexec/sbt-launch.jar clean test"/><property name="java.home" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre"/><property name="sun.arch.data.model" value="64"/><property name="user.language" value="en"/><property name="java.specification.vendor" value="Oracle Corporation"/><property name="awt.toolkit" value="sun.lwawt.macosx.LWCToolkit"/><property name="java.vm.info" value="mixed mode"/><property name="java.version" value="1.8.0_112"/><property name="java.ext.dirs" value="/Users/chrichiv/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"/><property name="sun.boot.class.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/classes"/><property name="java.vendor" value="Oracle Corporation"/><property name="file.separator" value="/"/><property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/><property name="sun.io.unicode.encoding" value="UnicodeBig"/><property name="sun.cpu.endian" value="little"/><property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/><property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/><property name="sun.cpu.isalist" value=""/>
    </properties>
                     <testcase classname="historical.HistoricalRecorderTest" name="Line should be accepted if route is in definitions or disregarded if not in definitions" time="39.26">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 30.139833678 seconds. Last failure message: 42014 was not equal to 2." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 30.139833678 seconds. Last failure message: 42014 was not equal to 2.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$1.apply(HistoricalRecorderTest.scala:52)
	at historical.HistoricalRecorderTest$$anonfun$1.apply(HistoricalRecorderTest.scala:36)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 42014 was not equal to 2
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$1$$anonfun$apply$1.apply(HistoricalRecorderTest.scala:54)
	at historical.HistoricalRecorderTest$$anonfun$1$$anonfun$apply$1.apply(HistoricalRecorderTest.scala:52)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Line should be accepted if bus stop is in definitions and rejected if not" time="33.892">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.095686921000002 seconds. Last failure message: 2527 was not equal to 2." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.095686921000002 seconds. Last failure message: 2527 was not equal to 2.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$2.apply(HistoricalRecorderTest.scala:79)
	at historical.HistoricalRecorderTest$$anonfun$2.apply(HistoricalRecorderTest.scala:62)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 2527 was not equal to 2
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$2$$anonfun$apply$2.apply(HistoricalRecorderTest.scala:81)
	at historical.HistoricalRecorderTest$$anonfun$2$$anonfun$apply$2.apply(HistoricalRecorderTest.scala:79)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Duplicate lines received within x seconds should not be processed" time="33.803">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.089858719 seconds. Last failure message: 1 was not equal to 3." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.089858719 seconds. Last failure message: 1 was not equal to 3.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$3.apply(HistoricalRecorderTest.scala:104)
	at historical.HistoricalRecorderTest$$anonfun$3.apply(HistoricalRecorderTest.scala:89)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 1 was not equal to 3
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$3$$anonfun$apply$3.apply(HistoricalRecorderTest.scala:106)
	at historical.HistoricalRecorderTest$$anonfun$3$$anonfun$apply$3.apply(HistoricalRecorderTest.scala:104)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Lines received with arrival time in past should be ignored" time="5.007">
                                                 <failure message="Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out" type="org.apache.http.conn.ConnectTimeoutException">org.apache.http.conn.ConnectTimeoutException: Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.getHttpResponse(BusDataSource.scala:80)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.&lt;init&gt;(BusDataSource.scala:64)
	at lbt.datasource.BusDataSource$BusDataSource.&lt;init&gt;(BusDataSource.scala:39)
	at datasource.TestDataSource.&lt;init&gt;(TestDataSource.scala:7)
	at historical.HistoricalRecorderTest$$anonfun$4.apply(HistoricalRecorderTest.scala:125)
	at historical.HistoricalRecorderTest$$anonfun$4.apply(HistoricalRecorderTest.scala:114)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 72 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="An actor should be created for each new vehicle received" time="3.604">
                                                 <failure message="Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out" type="org.apache.http.conn.ConnectTimeoutException">org.apache.http.conn.ConnectTimeoutException: Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.getHttpResponse(BusDataSource.scala:80)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.&lt;init&gt;(BusDataSource.scala:64)
	at lbt.datasource.BusDataSource$BusDataSource.&lt;init&gt;(BusDataSource.scala:39)
	at lbt.datasource.streaming.DataStreamProcessingController$.apply(DataStreamProcessingController.scala:86)
	at historical.HistoricalTestFixture.&lt;init&gt;(HistoricalTestFixture.scala:42)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:25)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 67 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicle actors should add incoming lines relating to arrival times to stop record" time="33.73">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.091325117 seconds. Last failure message: 23 was not equal to 47." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.091325117 seconds. Last failure message: 23 was not equal to 47.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$7.apply(HistoricalRecorderTest.scala:182)
	at historical.HistoricalRecorderTest$$anonfun$7.apply(HistoricalRecorderTest.scala:169)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 23 was not equal to 47
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$7$$anonfun$apply$6.apply(HistoricalRecorderTest.scala:184)
	at historical.HistoricalRecorderTest$$anonfun$7$$anonfun$apply$6.apply(HistoricalRecorderTest.scala:182)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicle actors should update record when closer arrival time is received" time="33.098">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 30.084061394 seconds. Last failure message: 24 was not equal to 48." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 30.084061394 seconds. Last failure message: 24 was not equal to 48.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$9.apply(HistoricalRecorderTest.scala:211)
	at historical.HistoricalRecorderTest$$anonfun$9.apply(HistoricalRecorderTest.scala:193)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 24 was not equal to 48
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$9$$anonfun$apply$7.apply(HistoricalRecorderTest.scala:213)
	at historical.HistoricalRecorderTest$$anonfun$9$$anonfun$apply$7.apply(HistoricalRecorderTest.scala:211)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicle actors should persist record if stop arrival time information is complete and passes validation" time="33.932">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 17 times over 31.068638227000005 seconds. Last failure message: 23 was not equal to 47." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 17 times over 31.068638227000005 seconds. Last failure message: 23 was not equal to 47.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$11.apply(HistoricalRecorderTest.scala:235)
	at historical.HistoricalRecorderTest$$anonfun$11.apply(HistoricalRecorderTest.scala:221)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 23 was not equal to 47
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$11$$anonfun$apply$8.apply(HistoricalRecorderTest.scala:237)
	at historical.HistoricalRecorderTest$$anonfun$11$$anonfun$apply$8.apply(HistoricalRecorderTest.scala:235)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Persisted record should be loaded with stop sequence in same order and with same values" time="33.99">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.107343794000002 seconds. Last failure message: 23 was not equal to 47." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.107343794000002 seconds. Last failure message: 23 was not equal to 47.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$13.apply(HistoricalRecorderTest.scala:264)
	at historical.HistoricalRecorderTest$$anonfun$13.apply(HistoricalRecorderTest.scala:250)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 23 was not equal to 47
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$13$$anonfun$apply$15.apply(HistoricalRecorderTest.scala:266)
	at historical.HistoricalRecorderTest$$anonfun$13$$anonfun$apply$15.apply(HistoricalRecorderTest.scala:264)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicle actors should not persist record if there is a gap in the sequence" time="4.859">
                                                 <failure message="Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out" type="org.apache.http.conn.ConnectTimeoutException">org.apache.http.conn.ConnectTimeoutException: Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.getHttpResponse(BusDataSource.scala:80)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.&lt;init&gt;(BusDataSource.scala:64)
	at lbt.datasource.BusDataSource$BusDataSource.&lt;init&gt;(BusDataSource.scala:39)
	at datasource.TestDataSource.&lt;init&gt;(TestDataSource.scala:7)
	at historical.HistoricalRecorderTest$$anonfun$16.apply(HistoricalRecorderTest.scala:288)
	at historical.HistoricalRecorderTest$$anonfun$16.apply(HistoricalRecorderTest.scala:278)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 72 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicle actors should persist record if there is a gap at the beginning of the sequence (bus started midway through route)" time="3.723">
                                                 <failure message="Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out" type="org.apache.http.conn.ConnectTimeoutException">org.apache.http.conn.ConnectTimeoutException: Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.getHttpResponse(BusDataSource.scala:80)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.&lt;init&gt;(BusDataSource.scala:64)
	at lbt.datasource.BusDataSource$BusDataSource.&lt;init&gt;(BusDataSource.scala:39)
	at lbt.datasource.streaming.DataStreamProcessingController$.apply(DataStreamProcessingController.scala:86)
	at historical.HistoricalTestFixture.&lt;init&gt;(HistoricalTestFixture.scala:42)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:25)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 67 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Multiple records should be persisted where the same bus on the same route makes the same journey at a different time" time="33.768">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.081437561999998 seconds. Last failure message: 31 was not equal to 94." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.081437561999998 seconds. Last failure message: 31 was not equal to 94.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$20.apply(HistoricalRecorderTest.scala:358)
	at historical.HistoricalRecorderTest$$anonfun$20.apply(HistoricalRecorderTest.scala:339)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 31 was not equal to 94
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$20$$anonfun$apply$36.apply(HistoricalRecorderTest.scala:360)
	at historical.HistoricalRecorderTest$$anonfun$20$$anonfun$apply$36.apply(HistoricalRecorderTest.scala:358)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Only one record should be persisted if multiple persists are requested for the same bus making the same route at the same time" time="32.955">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 30.073655225000003 seconds. Last failure message: 31 was not equal to 94." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 30.073655225000003 seconds. Last failure message: 31 was not equal to 94.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$23.apply(HistoricalRecorderTest.scala:392)
	at historical.HistoricalRecorderTest$$anonfun$23.apply(HistoricalRecorderTest.scala:374)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 31 was not equal to 94
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$23$$anonfun$apply$47.apply(HistoricalRecorderTest.scala:394)
	at historical.HistoricalRecorderTest$$anonfun$23$$anonfun$apply$47.apply(HistoricalRecorderTest.scala:392)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Record should not be duplicated in database if an updated last line is received after initial persist" time="33.711">
                                                 <failure message="The code passed to eventually never returned normally. Attempted 16 times over 31.083802583999997 seconds. Last failure message: 16 was not equal to 48." type="org.scalatest.exceptions.TestFailedDueToTimeoutException">org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 16 times over 31.083802583999997 seconds. Last failure message: 16 was not equal to 48.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
	at historical.HistoricalRecorderTest.eventually(HistoricalRecorderTest.scala:15)
	at historical.HistoricalRecorderTest$$anonfun$26.apply(HistoricalRecorderTest.scala:422)
	at historical.HistoricalRecorderTest$$anonfun$26.apply(HistoricalRecorderTest.scala:406)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.scalatest.exceptions.TestFailedException: 16 was not equal to 48
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at historical.HistoricalRecorderTest$$anonfun$26$$anonfun$apply$54.apply(HistoricalRecorderTest.scala:424)
	at historical.HistoricalRecorderTest$$anonfun$26$$anonfun$apply$54.apply(HistoricalRecorderTest.scala:422)
	at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
	... 61 more
</failure>
                                               </testcase><testcase classname="historical.HistoricalRecorderTest" name="Vehicles should persist and be shut down after specified period of inactivity" time="10.33">
                                                 <failure message="Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out" type="org.apache.http.conn.ConnectTimeoutException">org.apache.http.conn.ConnectTimeoutException: Connect to countdown.api.tfl.gov.uk:80 [countdown.api.tfl.gov.uk/168.63.37.98] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.getHttpResponse(BusDataSource.scala:80)
	at lbt.datasource.BusDataSource$BusDataSourceHttpClient.&lt;init&gt;(BusDataSource.scala:64)
	at lbt.datasource.BusDataSource$BusDataSource.&lt;init&gt;(BusDataSource.scala:39)
	at lbt.datasource.streaming.DataStreamProcessingController$.apply(DataStreamProcessingController.scala:86)
	at historical.HistoricalTestFixture.&lt;init&gt;(HistoricalTestFixture.scala:42)
	at historical.HistoricalRecorderTest$$anonfun$28.apply(HistoricalRecorderTest.scala:444)
	at historical.HistoricalRecorderTest$$anonfun$28.apply(HistoricalRecorderTest.scala:438)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$anonfun$apply$1.apply(TestSuite.scala:132)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.fixture.TestSuite$TestFunAndConfigMap.apply(TestSuite.scala:132)
	at historical.HistoricalRecorderTest.withFixture(HistoricalRecorderTest.scala:26)
	at org.scalatest.fixture.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:241)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:252)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.fixture.FunSuiteLike$class.runTest(FunSuiteLike.scala:252)
	at org.scalatest.fixture.FunSuite.runTest(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:312)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.fixture.FunSuiteLike$class.runTests(FunSuiteLike.scala:312)
	at org.scalatest.fixture.FunSuite.runTests(FunSuite.scala:226)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.fixture.FunSuite.org$scalatest$fixture$FunSuiteLike$$super$run(FunSuite.scala:226)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:316)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.fixture.FunSuiteLike$class.run(FunSuiteLike.scala:316)
	at org.scalatest.fixture.FunSuite.run(FunSuite.scala:226)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 73 more
</failure>
                                               </testcase>
                     <system-out></system-out>
                     <system-err></system-err>
                   </testsuite>